CREATE TABLE MACHINE_STATE
(
  MACHINE_ID  VARCHAR2(40 BYTE),
  START_TIME  DATE,
  END_TIME    DATE,
  STATE       VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SS_GOOD
(
  LINE_ID     VARCHAR2(40 BYTE),
  INPUT_TIME  TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONFIG
(
  TOTAL_TIME          NUMBER,
  PM_TIME             NUMBER,
  IDEA_OUTPUT_RATING  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LOT
(
  LOT_ID      VARCHAR2(40 BYTE),
  LINE_ID     VARCHAR2(40 BYTE),
  START_TIME  DATE,
  END_TIME    DATE,
  QTY_IN      INTEGER,
  QTY_OUT     INTEGER,
  QTY_REJ     INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALENDAR
(
  YEAR       VARCHAR2(4 BYTE),
  WW         VARCHAR2(2 BYTE),
  QUARTER    NUMBER,
  MONTH      NUMBER(10),
  STARTDATE  DATE,
  ENDDATE    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MACHINE_TIME
(
  MACHINE_ID  VARCHAR2(40 BYTE),
  LINE_ID     VARCHAR2(40 BYTE),
  TXNDATE     DATE,
  PROD_TIME   NUMBER,
  DOWN_TIME   NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SS_REJECT
(
  LINE_ID     VARCHAR2(40 BYTE),
  INPUT_TIME  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE OEE
(
  LINE_ID  VARCHAR2(40 BYTE),
  TXNDATE  DATE,
  WW       INTEGER,
  QUARTER  INTEGER,
  YEAR     INTEGER,
  AVAIL    INTEGER,
  PERF     NUMBER,
  QUAL     NUMBER,
  OEE      NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MACHINE
(
  MACHINE_ID   VARCHAR2(40 BYTE),
  DESCRIPTION  VARCHAR2(40 BYTE),
  LINE_ID      VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


